"use client";

import { useEffect, useState } from "react";
import { motion, useReducedMotion, type Variants } from "framer-motion";
import { Coffee, CupSoda, Croissant } from "lucide-react";

const container: Variants = {
  hidden: {},
  shown: { transition: { staggerChildren: 0.13, delayChildren: 0.15 } },
};
const item: Variants = {
  hidden: { opacity: 0, y: 14 },
  shown: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.2, 0.9, 0.2, 1] } },
};

// The one real hero object — a miniature browser frame showing an actual
// example of what Kodely generates, not an abstract graphic or skeleton
// blocks. The content assembles in (then gently re-assembles every few
// seconds) to literally show "watch it get built" — the approved
// reference design's signature hero motion.
export function HeroMock() {
  const reduced = useReducedMotion();
  const [cycle, setCycle] = useState(0);

  useEffect(() => {
    if (reduced) return;
    const id = setInterval(() => setCycle((c) => c + 1), 8000);
    return () => clearInterval(id);
  }, [reduced]);

  return (
    <div className="mx-auto w-full max-w-2xl" style={{ perspective: "1800px" }}>
      <div
        className="group overflow-hidden rounded-2xl border border-black/10 bg-white shadow-[0_40px_80px_-32px_rgba(0,0,0,0.25)] transition-transform duration-500 [transform:rotateX(4deg)] hover:[transform:rotateX(0deg)] dark:border-white/10 dark:bg-neutral-900"
      >
        <div className="flex items-center gap-2 border-b border-black/10 bg-black/[0.03] px-4 py-2.5 dark:border-white/10 dark:bg-white/[0.03]">
          <span className="h-2.5 w-2.5 rounded-full bg-black/15 dark:bg-white/15" />
          <span className="h-2.5 w-2.5 rounded-full bg-black/15 dark:bg-white/15" />
          <span className="h-2.5 w-2.5 rounded-full bg-black/15 dark:bg-white/15" />
          <div className="ml-3 flex-1 rounded-md bg-black/[0.04] px-3 py-1 text-center font-mono text-[11px] text-black/40 dark:bg-white/[0.06] dark:text-white/40">
            roan-coffee.kodely.site
          </div>
          <div className="hidden items-center gap-1.5 font-mono text-[10px] text-black/30 sm:flex dark:text-white/30">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.8)]" />
            Generated by Kodely
          </div>
        </div>

        <motion.div
          key={cycle}
          initial={reduced ? "shown" : "hidden"}
          animate="shown"
          variants={container}
          className="bg-[#fbf7f2] px-7 py-8 text-[#2a1f1a] dark:bg-[#1c1512] dark:text-[#f2e9e2]"
        >
          <motion.div variants={item} className="mb-8 flex items-center justify-between">
            <span className="text-sm font-semibold tracking-tight">Roan Coffee</span>
            <div className="flex gap-4 text-xs text-[#6b5347] dark:text-[#c9b3a5]">
              <span>Menu</span>
              <span>Visit</span>
            </div>
          </motion.div>

          <motion.p variants={item} className="text-[11px] font-medium uppercase tracking-[0.14em]" style={{ color: "var(--accent)" }}>
            Birch Street, Portland
          </motion.p>
          <motion.h3 variants={item} className="mt-2 text-2xl font-semibold leading-tight tracking-tight sm:text-3xl">
            Small-batch coffee,
            <br />
            roasted weekly.
          </motion.h3>
          <motion.div variants={item} className="mt-6 flex gap-3">
            <span className="rounded-lg bg-[#b5602f] px-4 py-2 text-xs font-medium text-white">See the menu</span>
            <span className="rounded-lg border border-[#b5602f]/30 px-4 py-2 text-xs font-medium text-[#b5602f]">
              Get directions
            </span>
          </motion.div>

          <motion.div variants={item} className="mt-7 grid grid-cols-3 gap-3">
            {[
              { name: "House Blend", price: "$4", Icon: Coffee },
              { name: "Cold Brew", price: "$5", Icon: CupSoda },
              { name: "Pastry Box", price: "$8", Icon: Croissant },
            ].map((p) => (
              <div key={p.name}>
                <div className="relative flex aspect-square items-center justify-center overflow-hidden rounded-lg border border-[#b5602f]/15 bg-gradient-to-br from-[#f3e7d4] via-[#e8d2ac] to-[#d8b183] dark:from-[#2a2019] dark:via-[#332419] dark:to-[#3f2c19]">
                  <p.Icon className="h-7 w-7 text-[#b5602f]/60 dark:text-[#e0a86a]/70" strokeWidth={1.5} />
                </div>
                <div className="mt-1.5 text-[11px] font-medium">{p.name}</div>
                <div className="text-[10px] text-[#8a7362] dark:text-[#b39d8a]">{p.price}</div>
              </div>
            ))}
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
}
